modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="vanillaarms"
version="1.0.0"
displayName="Vanilla Arms"
description='''Новое оружие, которое крафтится из ванильных материалов.'''

[[dependencies.vanillaarms]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.vanillaarms]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
